# Generated by Django 5.0.3 on 2026-04-01 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.UUIDField(db_index=True, help_text='UUID của Partner (soft link)')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền VNĐ', max_digits=12)),
                ('token_amount', models.IntegerField(help_text='Số token được quy đổi tương ứng')),
                ('payment_method', models.CharField(choices=[('payos', 'PayOS'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer')], help_text='Phương thức thanh toán', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Mã giao dịch từ cổng thanh toán', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'billing_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.UUIDField(db_index=True, help_text='UUID của Partner (soft link)')),
                ('service_id', models.UUIDField(help_text='UUID của Service đã tiêu token (soft link)')),
                ('tokens_used', models.IntegerField(help_text='Số token đã sử dụng')),
                ('cost', models.DecimalField(decimal_places=4, help_text='Chi phí tương ứng', max_digits=10)),
                ('conversation_id', models.CharField(blank=True, help_text='ID cuộc hội thoại liên quan (nếu có)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token Transaction',
                'verbose_name_plural': 'Token Transactions',
                'db_table': 'billing_token_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.UUIDField(db_index=True, help_text='UUID của Partner (soft link đến Partner Service)', unique=True)),
                ('available_tokens', models.IntegerField(default=0, help_text='Số token khả dụng hiện tại')),
                ('total_used', models.IntegerField(default=0, help_text='Tổng số token đã sử dụng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'billing_wallet',
            },
        ),
    ]
