# Generated by Django 5.0.3 on 2026-04-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='service_id',
            field=models.CharField(db_index=True, help_text='Mã định danh của Service tiêu token (vd: chatbot-ai-01)', max_length=255),
        ),
    ]
